admin:
  username: admin
  password: changeMe
  displayname: Admin

spring:
  datasource:
    url: jdbc:sqlite:db/todo.db

  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.SQLiteDialect

